CREATE TABLE `blog_posts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(256) NOT NULL,
	`title` varchar(256) NOT NULL,
	`subtitle` text,
	`content` text NOT NULL,
	`excerpt` text,
	`category` enum('trilhas-destinos','guias-praticos','planejamento-seguranca','equipamentos','conservacao-ambiental','historias-inspiracao') DEFAULT 'trilhas-destinos',
	`imageUrl` text,
	`images` json,
	`authorId` int,
	`authorName` varchar(128),
	`readingTime` int DEFAULT 5,
	`relatedTrailIds` json,
	`tags` json,
	`metaTitle` varchar(256),
	`metaDescription` text,
	`featured` int DEFAULT 0,
	`viewCount` int DEFAULT 0,
	`status` enum('draft','published') DEFAULT 'draft',
	`publishedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blog_posts_id` PRIMARY KEY(`id`),
	CONSTRAINT `blog_posts_slug_unique` UNIQUE(`slug`)
);
